### PR TITLE
Merge vistatest

### PR DESCRIPTION
**Pull request by JWinawer**
This pull request merges the vistatest branch into the master branch. The vistatest branch includes the new subdirectory vistatest, which is a copy of all files in the repository vistatest. The vistatest repository will become obsolete once merged into vistasoft.

### CODE REVIEW

**Comment by wandell** [comment]
I downloaded mergeVIstatest and ran mrvTest.  The function ran, but it produced the following log which contains some errors.  If I am understanding, then we should definitely merge vistatest, and we then we should separately track down these errors.

But before I merge, I would like Jon to confirm that my understanding is right.

------------------

Test suite: core
Test suite location: /Users/wandell/Github/vistasoft/mrTest/bold/core
26-Jan-2016 11:21:03


core

   test_Scripts
      test_Scripts .......................................... passed in     0.034597 seconds
   test_Scripts ............................................. passed in     0.042114 seconds


   test_Stats_fisherz
      test_Stats_fisherz .................................... passed in     0.342828 seconds
   test_Stats_fisherz ....................................... passed in     0.343899 seconds


   test_averagetSeries
      test_averagetSeries ................................... passed in    19.088552 seconds
   test_averagetSeries ...................................... passed in    19.090214 seconds


   test_betweenScansMotionComp
      test_betweenScansMotionComp ........................... passed in    51.823813 seconds
   test_betweenScansMotionComp .............................. passed in    51.827105 seconds


   test_corAnalFromInplane
      test_corAnalFromInplane ............................... passed in     1.991579 seconds
   test_corAnalFromInplane .................................. passed in     1.992810 seconds


   test_detrendTSeries
      test_detrendTSeries ................................... passed in     0.101314 seconds
   test_detrendTSeries ...................................... passed in     0.101948 seconds


   test_getCurDataROI
      test_getCurDataROI .................................... passed in     0.625409 seconds
   test_getCurDataROI ....................................... passed in     0.626021 seconds


   test_glm
      test_glm .............................................. FAILED in   173.297134 seconds
   test_glm ................................................. FAILED in   173.300412 seconds


   test_graphWin
      test_graphWin ......................................... passed in     0.408850 seconds
   test_graphWin ............................................ passed in     0.410167 seconds


   test_meanMapFromInplane
      test_meanMapFromInplane ............................... passed in     3.476884 seconds
   test_meanMapFromInplane .................................. passed in     3.477652 seconds


   test_mrInit
      test_mrInit ........................................... passed in     4.134215 seconds
   test_mrInit .............................................. passed in     4.136437 seconds


   test_mrvMigration
      test_mrvMigration ..................................... passed in    31.002762 seconds
   test_mrvMigration ........................................ passed in    31.004096 seconds


   test_niftiStruct
      test_niftiStruct ...................................... passed in     0.027624 seconds
   test_niftiStruct ......................................... passed in     0.028120 seconds


   test_normalizedMeanMapFromInplane
      test_normalizedMeanMapFromInplane ..................... passed in     0.374743 seconds
   test_normalizedMeanMapFromInplane ........................ passed in     0.375342 seconds


   test_plotMeanTSeries
      test_plotMeanTSeries .................................. passed in     4.687249 seconds
   test_plotMeanTSeries ..................................... passed in     4.687863 seconds


   test_prf
      test_prf .............................................. FAILED in    11.198647 seconds
   test_prf ................................................. FAILED in    11.199419 seconds


   test_tSeries4D
      test_tSeries4D ........................................ passed in    13.374414 seconds
   test_tSeries4D ........................................... passed in    13.375518 seconds


   test_viewGetHidden
      test_viewGetHidden .................................... passed in     0.545042 seconds
   test_viewGetHidden ....................................... passed in     0.545825 seconds


   test_viewGetInplane
      test_viewGetInplane ................................... passed in     4.912595 seconds
   test_viewGetInplane ...................................... passed in     4.913408 seconds


   test_withinScansMotionComp
      test_withinScansMotionComp ............................ passed in   102.804943 seconds
   test_withinScansMotionComp ............................... passed in   102.805696 seconds


   test_xformInplaneToVolume
      test_xformInplaneToVolume ............................. FAILED in    57.103805 seconds
   test_xformInplaneToVolume ................................ FAILED in    57.104798 seconds

core ........................................................ FAILED in   482.015472 seconds


===== Test Case Failure =====
Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m
Name:     test_glm

/Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m at <a href="matlab: opentoline('/Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m',83)">line 83</a>

Undefined function 'nanmax' for input arguments of type 'double'.


===== Test Case Failure =====
Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m
Name:     test_prf

/Applications/MATLAB_R2013b.app/toolbox/matlab/optimfun/optimset.m at <a href="matlab: opentoline('/Applications/MATLAB_R2013b.app/toolbox/matlab/optimfun/optimset.m',141)">line 141</a>
/Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmDefineParameters.m at <a href="matlab: opentoline('/Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmDefineParameters.m',572)">line 572</a>
/Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmMain.m at <a href="matlab: opentoline('/Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmMain.m',95)">line 95</a>
/Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m at <a href="matlab: opentoline('/Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m',61)">line 61</a>

No default options available: the function 'fmincon' does not exist on the path.


===== Test Case Failure =====
Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m
Name:     test_xformInplaneToVolume

/Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m at <a href="matlab: opentoline('/Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m',95)">line 95</a>

Undefined function 'nanmax' for input arguments of type 'single'.

-----------------------------------------
Environment information:
matlabVer: Image Processing Toolbox
matlabVer: MATLAB
matlabVer: MATLAB xUnit Test Framework
matlabVer: Statistical Parametric Mapping
computer: MACI64
vistaDir: /Users/wandell/Github/vistasoft/mrBOLD
vistaVer: Unversioned directory

**Comment by JWinawer** [comment]
Thanks for downloading and testing.

I agree with the conclusion - we should merge and then work out these
issues separately.

From a quick look at the log file, it looks like you do not have the
optimization toolbox, which is causing one or more problems with pRF
fitting (e.g., ' the function 'fmincon' does not exist on the path.') For
this, I think we either need to add a library check and spit out an error
earlier, or update the code so that it can run without the toolbox when it
is missing. But again, we should merge and then work this out in a separate
issue, as you suggest.

Jon

On Tue, Jan 26, 2016 at 2:43 PM, Brian Wandell <notifications@github.com>
wrote:

> I downloaded mergeVIstatest and ran mrvTest. The function ran, but it
> produced the following log which contains some errors. If I am
> understanding, then we should definitely merge vistatest, and we then we
> should separately track down these errors.
>
> But before I merge, I would like Jon to confirm that my understanding is
> right.
> ------------------------------
>
> Test suite: core
> Test suite location: /Users/wandell/Github/vistasoft/mrTest/bold/core
> 26-Jan-2016 11:21:03
>
> core
>
> test_Scripts
> test_Scripts .......................................... passed in 0.034597
> seconds
> test_Scripts ............................................. passed in
> 0.042114 seconds
>
> test_Stats_fisherz
> test_Stats_fisherz .................................... passed in 0.342828
> seconds
> test_Stats_fisherz ....................................... passed in
> 0.343899 seconds
>
> test_averagetSeries
> test_averagetSeries ................................... passed in
> 19.088552 seconds
> test_averagetSeries ...................................... passed in
> 19.090214 seconds
>
> test_betweenScansMotionComp
> test_betweenScansMotionComp ........................... passed in
> 51.823813 seconds
> test_betweenScansMotionComp .............................. passed in
> 51.827105 seconds
>
> test_corAnalFromInplane
> test_corAnalFromInplane ............................... passed in 1.991579
> seconds
> test_corAnalFromInplane .................................. passed in
> 1.992810 seconds
>
> test_detrendTSeries
> test_detrendTSeries ................................... passed in 0.101314
> seconds
> test_detrendTSeries ...................................... passed in
> 0.101948 seconds
>
> test_getCurDataROI
> test_getCurDataROI .................................... passed in 0.625409
> seconds
> test_getCurDataROI ....................................... passed in
> 0.626021 seconds
>
> test_glm
> test_glm .............................................. FAILED in
> 173.297134 seconds
> test_glm ................................................. FAILED in
> 173.300412 seconds
>
> test_graphWin
> test_graphWin ......................................... passed in 0.408850
> seconds
> test_graphWin ............................................ passed in
> 0.410167 seconds
>
> test_meanMapFromInplane
> test_meanMapFromInplane ............................... passed in 3.476884
> seconds
> test_meanMapFromInplane .................................. passed in
> 3.477652 seconds
>
> test_mrInit
> test_mrInit ........................................... passed in 4.134215
> seconds
> test_mrInit .............................................. passed in
> 4.136437 seconds
>
> test_mrvMigration
> test_mrvMigration ..................................... passed in
> 31.002762 seconds
> test_mrvMigration ........................................ passed in
> 31.004096 seconds
>
> test_niftiStruct
> test_niftiStruct ...................................... passed in 0.027624
> seconds
> test_niftiStruct ......................................... passed in
> 0.028120 seconds
>
> test_normalizedMeanMapFromInplane
> test_normalizedMeanMapFromInplane ..................... passed in 0.374743
> seconds
> test_normalizedMeanMapFromInplane ........................ passed in
> 0.375342 seconds
>
> test_plotMeanTSeries
> test_plotMeanTSeries .................................. passed in 4.687249
> seconds
> test_plotMeanTSeries ..................................... passed in
> 4.687863 seconds
>
> test_prf
> test_prf .............................................. FAILED in
> 11.198647 seconds
> test_prf ................................................. FAILED in
> 11.199419 seconds
>
> test_tSeries4D
> test_tSeries4D ........................................ passed in
> 13.374414 seconds
> test_tSeries4D ........................................... passed in
> 13.375518 seconds
>
> test_viewGetHidden
> test_viewGetHidden .................................... passed in 0.545042
> seconds
> test_viewGetHidden ....................................... passed in
> 0.545825 seconds
>
> test_viewGetInplane
> test_viewGetInplane ................................... passed in 4.912595
> seconds
> test_viewGetInplane ...................................... passed in
> 4.913408 seconds
>
> test_withinScansMotionComp
> test_withinScansMotionComp ............................ passed in
> 102.804943 seconds
> test_withinScansMotionComp ............................... passed in
> 102.805696 seconds
>
> test_xformInplaneToVolume
> test_xformInplaneToVolume ............................. FAILED in
> 57.103805 seconds
> test_xformInplaneToVolume ................................ FAILED in
> 57.104798 seconds
>
> core ........................................................ FAILED in
> 482.015472 seconds
>
> ===== Test Case Failure =====
> Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m
> Name: test_glm
>
> /Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m at line 83
>
> Undefined function 'nanmax' for input arguments of type 'double'.
>
> ===== Test Case Failure =====
> Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m
> Name: test_prf
>
> /Applications/MATLAB_R2013b.app/toolbox/matlab/optimfun/optimset.m at line
> 141
> /Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmDefineParameters.m
> at line 572
> /Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmMain.m
> at line 95
> /Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m at line 61
>
> No default options available: the function 'fmincon' does not exist on the
> path.
>
> ===== Test Case Failure =====
> Location:
> /Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m
> Name: test_xformInplaneToVolume
>
> /Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m
> at line 95
>
> Undefined function 'nanmax' for input arguments of type 'single'.
> ------------------------------
>
> Environment information:
> matlabVer: Image Processing Toolbox
> matlabVer: MATLAB
> matlabVer: MATLAB xUnit Test Framework
> matlabVer: Statistical Parametric Mapping
> computer: MACI64
> vistaDir: /Users/wandell/Github/vistasoft/mrBOLD
> vistaVer: Unversioned directory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/pull/161#issuecomment-175195353>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Comment by arokem** [comment]
Quick question: do you really want to merge in all of that external testing
toolbox (xunit)? Looks like Matlab has a lot of these things implemented as
part of their product these days:
http://www.mathworks.com/help/matlab/matlab-unit-test-framework.html

On Tue, Jan 26, 2016 at 11:57 AM, Jonathan Winawer <notifications@github.com

**Comment by JWinawer** [comment]
That's a good question. I guess the answer would depend on how hard it
would be to recode the validation tests using Matlab's new unit testing
code. The advantage of the external toolbox and existing validation code is
that it exists and runs. On the other hand, it is not that extensive -
there are 22 BOLD validation tests.  If recoding is not that cumbersome,
then that is probably better. I will look into it when I have a chance. If
you want to check, look at any of the functions in the
folder mrTest/bold/core.


On Tue, Jan 26, 2016 at 4:15 PM, Ariel Rokem <notifications@github.com>
wrote:

> Quick question: do you really want to merge in all of that external testing
> toolbox (xunit)? Looks like Matlab has a lot of these things implemented as
> part of their product these days:
> http://www.mathworks.com/help/matlab/matlab-unit-test-framework.html
>
> On Tue, Jan 26, 2016 at 11:57 AM, Jonathan Winawer <
> notifications@github.com
> > wrote:
>
> > Thanks for downloading and testing.
> >
> > I agree with the conclusion - we should merge and then work out these
> > issues separately.
> >
> > From a quick look at the log file, it looks like you do not have the
> > optimization toolbox, which is causing one or more problems with pRF
> > fitting (e.g., ' the function 'fmincon' does not exist on the path.') For
> > this, I think we either need to add a library check and spit out an error
> > earlier, or update the code so that it can run without the toolbox when
> it
> > is missing. But again, we should merge and then work this out in a
> separate
> > issue, as you suggest.
> >
> > Jon
> >
> > On Tue, Jan 26, 2016 at 2:43 PM, Brian Wandell <notifications@github.com
> >
> > wrote:
> >
> > > I downloaded mergeVIstatest and ran mrvTest. The function ran, but it
> > > produced the following log which contains some errors. If I am
> > > understanding, then we should definitely merge vistatest, and we then
> we
> > > should separately track down these errors.
> > >
> > > But before I merge, I would like Jon to confirm that my understanding
> is
> > > right.
> > > ------------------------------
>
> >
> > >
> > > Test suite: core
> > > Test suite location: /Users/wandell/Github/vistasoft/mrTest/bold/core
> > > 26-Jan-2016 11:21:03
> > >
> > > core
> > >
> > > test_Scripts
> > > test_Scripts .......................................... passed in
> > 0.034597
> > > seconds
> > > test_Scripts ............................................. passed in
> > > 0.042114 seconds
> > >
> > > test_Stats_fisherz
> > > test_Stats_fisherz .................................... passed in
> > 0.342828
> > > seconds
> > > test_Stats_fisherz ....................................... passed in
> > > 0.343899 seconds
> > >
> > > test_averagetSeries
> > > test_averagetSeries ................................... passed in
> > > 19.088552 seconds
> > > test_averagetSeries ...................................... passed in
> > > 19.090214 seconds
> > >
> > > test_betweenScansMotionComp
> > > test_betweenScansMotionComp ........................... passed in
> > > 51.823813 seconds
> > > test_betweenScansMotionComp .............................. passed in
> > > 51.827105 seconds
> > >
> > > test_corAnalFromInplane
> > > test_corAnalFromInplane ............................... passed in
> > 1.991579
> > > seconds
> > > test_corAnalFromInplane .................................. passed in
> > > 1.992810 seconds
> > >
> > > test_detrendTSeries
> > > test_detrendTSeries ................................... passed in
> > 0.101314
> > > seconds
> > > test_detrendTSeries ...................................... passed in
> > > 0.101948 seconds
> > >
> > > test_getCurDataROI
> > > test_getCurDataROI .................................... passed in
> > 0.625409
> > > seconds
> > > test_getCurDataROI ....................................... passed in
> > > 0.626021 seconds
> > >
> > > test_glm
> > > test_glm .............................................. FAILED in
> > > 173.297134 seconds
> > > test_glm ................................................. FAILED in
> > > 173.300412 seconds
> > >
> > > test_graphWin
> > > test_graphWin ......................................... passed in
> > 0.408850
> > > seconds
> > > test_graphWin ............................................ passed in
> > > 0.410167 seconds
> > >
> > > test_meanMapFromInplane
> > > test_meanMapFromInplane ............................... passed in
> > 3.476884
> > > seconds
> > > test_meanMapFromInplane .................................. passed in
> > > 3.477652 seconds
> > >
> > > test_mrInit
> > > test_mrInit ........................................... passed in
> > 4.134215
> > > seconds
> > > test_mrInit .............................................. passed in
> > > 4.136437 seconds
> > >
> > > test_mrvMigration
> > > test_mrvMigration ..................................... passed in
> > > 31.002762 seconds
> > > test_mrvMigration ........................................ passed in
> > > 31.004096 seconds
> > >
> > > test_niftiStruct
> > > test_niftiStruct ...................................... passed in
> > 0.027624
> > > seconds
> > > test_niftiStruct ......................................... passed in
> > > 0.028120 seconds
> > >
> > > test_normalizedMeanMapFromInplane
> > > test_normalizedMeanMapFromInplane ..................... passed in
> > 0.374743
> > > seconds
> > > test_normalizedMeanMapFromInplane ........................ passed in
> > > 0.375342 seconds
> > >
> > > test_plotMeanTSeries
> > > test_plotMeanTSeries .................................. passed in
> > 4.687249
> > > seconds
> > > test_plotMeanTSeries ..................................... passed in
> > > 4.687863 seconds
> > >
> > > test_prf
> > > test_prf .............................................. FAILED in
> > > 11.198647 seconds
> > > test_prf ................................................. FAILED in
> > > 11.199419 seconds
> > >
> > > test_tSeries4D
> > > test_tSeries4D ........................................ passed in
> > > 13.374414 seconds
> > > test_tSeries4D ........................................... passed in
> > > 13.375518 seconds
> > >
> > > test_viewGetHidden
> > > test_viewGetHidden .................................... passed in
> > 0.545042
> > > seconds
> > > test_viewGetHidden ....................................... passed in
> > > 0.545825 seconds
> > >
> > > test_viewGetInplane
> > > test_viewGetInplane ................................... passed in
> > 4.912595
> > > seconds
> > > test_viewGetInplane ...................................... passed in
> > > 4.913408 seconds
> > >
> > > test_withinScansMotionComp
> > > test_withinScansMotionComp ............................ passed in
> > > 102.804943 seconds
> > > test_withinScansMotionComp ............................... passed in
> > > 102.805696 seconds
> > >
> > > test_xformInplaneToVolume
> > > test_xformInplaneToVolume ............................. FAILED in
> > > 57.103805 seconds
> > > test_xformInplaneToVolume ................................ FAILED in
> > > 57.104798 seconds
> > >
> > > core ........................................................ FAILED in
> > > 482.015472 seconds
> > >
> > > ===== Test Case Failure =====
> > > Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m
> > > Name: test_glm
> > >
> > > /Users/wandell/Github/vistasoft/mrTest/bold/core/test_glm.m at line 83
> > >
> > > Undefined function 'nanmax' for input arguments of type 'double'.
> > >
> > > ===== Test Case Failure =====
> > > Location: /Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m
> > > Name: test_prf
> > >
> > > /Applications/MATLAB_R2013b.app/toolbox/matlab/optimfun/optimset.m at
> > line
> > > 141
> > >
> >
> /Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmDefineParameters.m
> > > at line 572
> > >
> /Users/wandell/Github/vistasoft/mrBOLD/Analysis/retinotopyModel/rmMain.m
> > > at line 95
> > > /Users/wandell/Github/vistasoft/mrTest/bold/core/test_prf.m at line 61
> > >
> > > No default options available: the function 'fmincon' does not exist on
> > the
> > > path.
> > >
> > > ===== Test Case Failure =====
> > > Location:
> > >
> >
> /Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m
> > > Name: test_xformInplaneToVolume
> > >
> > >
> >
> /Users/wandell/Github/vistasoft/mrTest/bold/core/test_xformInplaneToVolume.m
> > > at line 95
> > >
> > > Undefined function 'nanmax' for input arguments of type 'single'.
> > > ------------------------------
> > >
> > > Environment information:
> > > matlabVer: Image Processing Toolbox
> > > matlabVer: MATLAB
> > > matlabVer: MATLAB xUnit Test Framework
> > > matlabVer: Statistical Parametric Mapping
> > > computer: MACI64
> > > vistaDir: /Users/wandell/Github/vistasoft/mrBOLD
> > > vistaVer: Unversioned directory
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vistalab/vistasoft/pull/161#issuecomment-175195353
> >.
> > >
> >
> >
> >
> > --
> > Jonathan Winawer
> > Assistant Professor of Psychology and Neural Science
> >
> > New York University
> > 6 Washington Place
> > New York, NY, 10003
> > (212) 998-7922 (phone)
> > (212) 995-4018 (fax)
> > jonathan.winawer@nyu.edu
> > http://psych.nyu.edu/winawer/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vistalab/vistasoft/pull/161#issuecomment-175200670>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vistalab/vistasoft/pull/161#issuecomment-175233138>.
>



-- 
Jonathan Winawer
Assistant Professor of Psychology and Neural Science

New York University
6 Washington Place
New York, NY, 10003
(212) 998-7922 (phone)
(212) 995-4018 (fax)
jonathan.winawer@nyu.edu
http://psych.nyu.edu/winawer/

**Pull request merged**
